In [ ]:
introduction to python libraries :

In [ ]:
class ------>

In [ ]:
Group of class are written in a single file togther all those are called as modules.

In [ ]:
Group of moduules togther are called as library.

In [ ]:
introduction to Numpy :

In [ ]:
Numpy stands for Numerical python.

It will be acting as the foundational library in python.

It is used for all the numerical computation and sceintific computations in mutiple domains.

Numpy in shotform will be defined as np.

It is having a datatype called as an array.

In [1]:
import numpy as np  # np is an alias...

In [ ]:
array : It is an object defined in numpy  is an N - Dimesional array called ndarray

In [2]:
a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [6]:
# printing a 2d array :

b = np.array([[1,2],[3,4]])

print(b)

[[1 2]
 [3 4]]


In [ ]:
# req : i want to print an array of 20 numbers.

In [8]:
a = np.arange(21)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
Note : last value is always exclusive.

In [ ]:
# knowing the size.

In [9]:
print(a.itemsize)

8


In [ ]:
Array of zeros>

In [10]:
x = np.zeros(5)

print(x)

[0. 0. 0. 0. 0.]


In [11]:
x = np.zeros((4,5))  # (x,y) ===>  x is for rows and y is for cols.

print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
Array of ones.

In [12]:
y = np.ones((3,4))

print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
what is the between list and array, if given both to you what do you choose? why and explain?

In [ ]:
reason : storage and internal memroy allocation.

In [ ]:
Statical computing in Numpy: